
services:
  db:
    image: postgres:16
    restart: always
    container_name: yells-post-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    restart: always
    container_name: yells-post-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgres://${DB_USER}:${POSTGRES_PASSWORD}@db:${DB_PORT}/${DB_NAME}?sslmode=disable"
    ports:
      - "8080:8080"

volumes:
  db_data: