// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID       string     `json:"id"`
	Text     string     `json:"text"`
	Author   string     `json:"author"`
	ParentID *string    `json:"parentID,omitempty"`
	Replies  []*Comment `json:"replies"`
}

type Mutation struct {
}

type Post struct {
	ID            string     `json:"id"`
	Title         string     `json:"title"`
	Content       string     `json:"content"`
	Comments      []*Comment `json:"comments"`
	AllowComments bool       `json:"allowComments"`
}

type Query struct {
}

type Subscription struct {
}
